# Generated by Django 4.2.23 on 2025-06-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0023_alter_family_head_insuree'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuree',
            name='middle_name',
            field=models.CharField(blank=True, db_column='MiddleName', max_length=100, null=True),
        ),
    ]
