# Generated by Django 4.2.23 on 2025-06-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0024_insuree_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuree',
            name='disability_status',
            field=models.CharField(blank=True, choices=[('no_disability', 'No Disability'), ('physical_disability', 'Physical Disability'), ('visual_impairment', 'Visual Impairment'), ('hearing_impairment', 'Hearing Impairment'), ('speech_disability', 'Speech Disability'), ('intellectual_disability', 'Intellectual Disability'), ('mental_disorder', 'Mental Disorder'), ('autism_spectrum_disorder', 'Autism Spectrum Disorder'), ('cerebral_palsy', 'Cerebral Palsy'), ('multiple_sclerosis', 'Multiple Sclerosis'), ('parkinsons_disease', "Parkinson's Disease"), ('spinal_cord_injury', 'Spinal Cord Injury'), ('amputation', 'Amputation'), ('chronic_neurological_condition', 'Chronic Neurological Condition'), ('other_disability', 'Other Disability')], db_column='DisabilityStatus', default='no_disability', max_length=50, null=True),
        ),
    ]
