# Generated by Django 4.2.23 on 2025-06-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0025_insuree_disability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuree',
            name='is_active',
            field=models.BooleanField(db_column='IsActive', default=True, help_text='Indicates whether the insuree is currently active'),
        ),
    ]
