# Generated by Django 4.2.23 on 2025-06-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0026_insuree_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuree',
            name='is_deleted',
            field=models.BooleanField(db_column='IsDeleted', default=False, help_text='Indicates whether the insuree has been soft deleted'),
        ),
    ]
