# Generated by Django 4.2.23 on 2025-07-08 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_membership_types'),
        ('insuree', '0027_insuree_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='insureepolicy',
            name='membership_type',
            field=models.ForeignKey(blank=True, db_column='MembershipTypeId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.membershiptype'),
        ),
    ]
