# Generated by Django 4.2.23 on 2025-08-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0028_insureepolicy_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuree',
            name='legacy_chf_id',
            field=models.CharField(blank=True, db_column='LegacyCHFID', db_index=True, max_length=50, null=True),
        ),
    ]
