# Generated by Django 4.2.23 on 2025-08-28 12:02

import core.fields
import core.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_mutationlog_client_mutation_id'),
        ('location', '0020_healthfacility_bank_account'),
        ('insuree', '0029_insuree_legacy_chf_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsureeIdReservation',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=36, unique=True)),
                ('chf_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('reserved_by_user_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RS', 'Reserved'), ('US', 'Used'), ('CA', 'Cancelled')], default='RS', max_length=2)),
                ('reserved_hf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reserved_insuree_ids', to='location.healthfacility')),
                ('reserved_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reserved_insuree_ids', to='core.officer')),
                ('used_by_insuree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='used_reservations', to='insuree.insuree')),
            ],
            options={
                'db_table': 'insuree_IdReservation',
                'managed': True,
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
    ]
