# Generated by Django 4.2.23 on 2025-08-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0030_insureeidreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='insureeidreservation',
            name='audit_user_id',
            field=models.IntegerField(blank=True, db_column='AuditUserID', null=True),
        ),
    ]
