# Generated by Django 4.2.25 on 2025-11-20 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0024_merge_20251031_1301'),
        ('insuree', '0031_insureeidreservation_audit_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsureeCheckIn',
            fields=[
                ('id', models.AutoField(db_column='InsureeCheckInID', primary_key=True, serialize=False)),
                ('check_in_date', models.DateTimeField(blank=True, db_column='CheckInDate', null=True)),
                ('audit_user_id', models.IntegerField(blank=True, db_column='AuditUserID', null=True)),
                ('health_facility', models.ForeignKey(db_column='HFID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='insuree_checkins', to='location.healthfacility')),
                ('insuree', models.ForeignKey(db_column='InsureeID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='checkins', to='insuree.insuree')),
            ],
            options={
                'db_table': 'tblInsureeCheckIn',
                'managed': True,
            },
        ),
    ]
