# Generated by Django 4.2.25 on 2025-12-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0032_insureecheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='insureecheckin',
            name='is_deleted',
            field=models.BooleanField(db_column='IsDeleted', default=False),
        ),
    ]
