# Generated by Django 4.2.25 on 2026-01-30 08:00

import core.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0033_insureecheckin_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuree',
            name='enrollment_date',
            field=core.fields.DateTimeField(db_column='EnrollmentDate', default=django.utils.timezone.now),
        ),
    ]
