# Generated by Django 4.2.25 on 2026-01-30 08:27

import core.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insuree', '0034_insuree_enrollment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='enrollment_date',
            field=core.fields.DateTimeField(db_column='EnrollmentDate', default=django.utils.timezone.now),
        ),
    ]
